spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tim_remake
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
#mapper文件位置配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yep.server.pojo
logging:
  level:
    com.yep.server.controller: debug
    com.yep.server.service: debug
    com.yep.server.mapper: debug
