spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tim_remake
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
  rabbitmq:
    publisher-returns: true
    publisher-confirm-type: correlated
  resources:
    static-locations: file:${file.dir}
#mapper文件位置配置
logging:
  level:
    com.yep.server.controller: debug
    com.yep.server.service: debug
    com.yep.server.mapper: debug
    com.yep.server.utils: debug
  file:
#       path: G:\workspace\workspace_myIdea\TimChatRemake\TimChatRemake-server\logs #本机环境
    path: /usr/local #服务器
#fastdfs:
#  nginx:
#    host: http://192.168.111.135/ #本机环境
#       host: http://127.0.0.1 #服务器
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yep.server.pojo
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8082 #和前端对接
file:
#   dir: G:\workspace\workspace_myIdea\TimChatRemake\TimChatRemake-server\file
      dir: /usr/local